name: Project CI-CD Pipeline

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout ğŸ”
        uses: actions/checkout@v1

      - name: Install dependencies ğŸ
        run: yarn

      - name: Running tests ğŸ§ª
        run: yarn test

      - name: Build the project ğŸ—ï¸
        run: yarn build

      - name: Deploying ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
